name: static check
on: pull_request

jobs:
  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: senorprogrammer/golang-github-actions@2614d7f
      with:
        run: imports
        token: ${{ secrets.GITHUB_TOKEN }}

  errcheck:
    name: Errcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: senorprogrammer/golang-github-actions@2614d7f
      with:
        run: errcheck
        token: ${{ secrets.GITHUB_TOKEN }}

  #lint:
    #name: Lint
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@master
    #- name: check
      #uses: senorprogrammer/golang-github-actions@2614d7f
      #with:
        #run: lint
        #token: ${{ secrets.GITHUB_TOKEN }}

  shadow:
    name: Shadow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: senorprogrammer/golang-github-actions@2614d7f
      with:
        run: shadow
        token: ${{ secrets.GITHUB_TOKEN }}

  staticcheck:
    name: StaticCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: senorprogrammer/golang-github-actions@2614d7f
      with:
        run: staticcheck
        token: ${{ secrets.GITHUB_TOKEN }}

  #sec:
    #name: Sec
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@master
    #- name: check
      #uses: senorprogrammer/golang-github-actions@2614d7f
      #with:
        #run: sec
        #token: ${{ secrets.GITHUB_TOKEN }}
        #flags: "-exclude=G104"
